# Generated by Django 4.0.3 on 2022-04-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_language', models.CharField(max_length=100)),
                ('foreign_language', models.CharField(max_length=100)),
                ('example_of_use', models.TextField(null=True)),
                ('is_learned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WordGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('words', models.ManyToManyField(to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
                ('word_groups', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='words.wordgroup')),
            ],
        ),
    ]
