# Generated by Django 4.0.3 on 2022-04-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_remove_languages_word_groups_wordgroup_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='example_of_use',
            field=models.TextField(blank=True, null=True),
        ),
    ]
