# Generated by Django 4.0.3 on 2022-04-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_word_example_of_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
