# Generated by Django 4.0.3 on 2022-04-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_word_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
    ]
