# Generated by Django 4.0.3 on 2022-04-13 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0007_word_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
        migrations.AddField(
            model_name='wordgroup',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
