# Generated by Django 4.0.3 on 2022-04-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_remove_word_user_wordgroup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordgroup',
            name='words',
        ),
        migrations.AddField(
            model_name='wordgroup',
            name='words',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='words.word'),
        ),
    ]
