# Generated by Django 4.0.3 on 2022-04-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_remove_wordgroup_words_wordgroup_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordgroup',
            name='words',
        ),
        migrations.AddField(
            model_name='wordgroup',
            name='words',
            field=models.ManyToManyField(to='words.word'),
        ),
    ]
