# Generated by Django 4.0.3 on 2022-04-20 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0010_remove_wordgroup_words_wordgroup_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='words.languages')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('word_group', models.ManyToManyField(to='words.wordgroup')),
            ],
        ),
    ]
