# Generated by Django 4.0.3 on 2022-04-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0014_post_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
