# Generated by Django 4.0.3 on 2022-04-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0015_remove_post_course_delete_course_delete_post'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='flashcards',
            field=models.ManyToManyField(related_name='flashcards', to='words.wordgroup'),
        ),
    ]
